CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(80) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "created_at" datetime DEFAULT (now())
);

CREATE TABLE "videos" (
  "video_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "year" date NOT NULL,
  "autor_id" int NOT NULL
);

CREATE TABLE "authors" (
  "author_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text
);

CREATE TABLE "collaborators" (
  "collaborator_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "video_id" int NOT NULL
);

CREATE TABLE "comments" (
  "comment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" text NOT NULL,
  "video_id" int NOT NULL,
  "user_id" int NOT NULL,
  "published_date" datetime DEFAULT (now())
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" text,
  "starts" int NOT NULL CHECK (starts BETWEEN 1 AND 5),
  "user_id" int NOT NULL,
  "video_id" int NOT NULL
);

ALTER TABLE "videos" ADD FOREIGN KEY ("autor_id") REFERENCES "authors" ("author_id");

ALTER TABLE "collaborators" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("video_id");

ALTER TABLE "comments" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("video_id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("video_id");
